schema: spec-driven
created: 2026-10-07
created_by: fishon100 <75553274+fishon100@users.noreply.github.com>
archived_by: fishon100 <75553274+fishon100@users.noreply.github.com>
archived_at: 2026-10-07
